version: '3.8'

services:
  main-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./saves:/opt/factorio/saves
      - ./mods:/opt/factorio/mods
      - ./config:/opt/factorio/config
    network_mode: "host"
