version: '3.9'

services:
  main-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    image: fac_server
    volumes:
      - ./saves:/opt/factorio/saves
      - ./mods:/opt/factorio/mods
      - ./config:/opt/factorio/config
      - ./log:/opt/factorio/log
    network_mode: host
    restart: always
